# src/utils/verificador_facial.py

import numpy as np
import json
from scipy.spatial.distance import cosine
from src.config.db import get_connection

UMBRAL_SIMILITUD = 0.4  # Ajusta seg√∫n pruebas

def verificar_embedding(nuevo_embedding):
    try:
        connection = get_connection()
        cursor = connection.cursor(dictionary=True)
        cursor.execute("SELECT id_usuario, embedding FROM reconocimiento_facial")
        registros = cursor.fetchall()
        print(f"üìö {len(registros)} embeddings existentes recuperados")

        for row in registros:
            try:
                emb_db = np.array(json.loads(row["embedding"]))
                distancia = cosine(nuevo_embedding, emb_db)
                print(f"üîç Comparando con ID usuario {row['id_usuario']} | Distancia: {distancia}")

                if distancia < UMBRAL_SIMILITUD:
                    print(f"‚úÖ Coincidencia detectada con usuario {row['id_usuario']}")
                    return {
                        "match": True,
                        "id_usuario": row["id_usuario"],
                        "distancia": distancia
                    }
            except Exception as err:
                print("‚ö†Ô∏è Error al comparar embedding:", err)

        print("‚úÖ No se encontr√≥ coincidencia.")
        return {"match": False}

    except Exception as e:
        print("‚ùå Error al verificar embedding:", str(e))
        return {"match": False, "error": str(e)}
